In [2]:
#Making use of KNN for classification

In [3]:
#Importing neccessary libraries.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
plt.style.use('seaborn-whitegrid')
%matplotlib inline
import seaborn as sns
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA 
import pylab as pl
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsClassifier
print("setup right")

setup right


In [4]:
#loading the dataset 
tomato_data = pd.read_csv(r'C:\Users\joseph\Documents\tomato_data.csv')
tomato_data.head(3)

TOMATO ID  LONGEVITY(IN DAYS)  TEXTURE  COLOUR  QUALITY(5 STAR )
0          1                   1        1       3                 5
1          2                   1        1       3                 5
2          3                   1        1       2                 5

In [5]:
#checking for null/nan values.
tomato_data.isnull().values.any()

False

In [6]:
tomato_data.info()
tomato_data.columns

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 615 entries, 0 to 614
Data columns (total 5 columns):
TOMATO ID             615 non-null int64
LONGEVITY(IN DAYS)    615 non-null int64
TEXTURE               615 non-null int64
COLOUR                615 non-null int64
QUALITY(5 STAR )      615 non-null int64
dtypes: int64(5)
memory usage: 24.1 KB


Index(['TOMATO ID', 'LONGEVITY(IN DAYS)', 'TEXTURE', 'COLOUR',
       'QUALITY(5 STAR )'],
      dtype='object')

In [7]:
tomato_data.shape

(615, 5)

In [8]:
tomato_data.describe()

TOMATO ID  LONGEVITY(IN DAYS)     TEXTURE      COLOUR  \
count  615.000000          615.000000  615.000000  615.000000   
mean   308.000000            3.655285    1.736585    2.817886   
std    177.679487            1.884672    0.802406    0.418628   
min      1.000000            1.000000    1.000000    1.000000   
25%    154.500000            2.000000    1.000000    3.000000   
50%    308.000000            4.000000    2.000000    3.000000   
75%    461.500000            5.000000    2.000000    3.000000   
max    615.000000            7.000000    3.000000    3.000000   

       QUALITY(5 STAR )  
count        615.000000  
mean           4.182114  
std            0.857619  
min            3.000000  
25%            3.000000  
50%            4.000000  
75%            5.000000  
max            5.000000

In [9]:
tomato_data.corr()

TOMATO ID  LONGEVITY(IN DAYS)   TEXTURE    COLOUR  \
TOMATO ID            1.000000            0.985435  0.619521  0.156382   
LONGEVITY(IN DAYS)   0.985435            1.000000  0.630193  0.176272   
TEXTURE              0.619521            0.630193  1.000000  0.201202   
COLOUR               0.156382            0.176272  0.201202  1.000000   
QUALITY(5 STAR )    -0.625702           -0.618073 -0.850823 -0.143364   

                    QUALITY(5 STAR )  
TOMATO ID                  -0.625702  
LONGEVITY(IN DAYS)         -0.618073  
TEXTURE                    -0.850823  
COLOUR                     -0.143364  
QUALITY(5 STAR )            1.000000

In [10]:
#Need to drop Tomato ID, Colour.
tomato_data.drop("TOMATO ID", axis=1,inplace=True)
tomato_data.drop("COLOUR", axis=1,inplace=True)

In [11]:
tomato_data.columns

Index(['LONGEVITY(IN DAYS)', 'TEXTURE', 'QUALITY(5 STAR )'], dtype='object')

In [19]:
#Dividing the data into attributes and labels.
X = tomato_data.drop('QUALITY(5 STAR )', axis=1)
y = tomato_data['QUALITY(5 STAR )']
#X_test.fillna(X_train.mean(), inplace=True)

#The final preprocessing step is to divide our data into training and test sets.
# Import train_test_split function
from sklearn.model_selection import train_test_split#Import knearest neighbors Classifier model
from sklearn.neighbors import KNeighborsClassifier

# Splitting the dataset into training and test set.  
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size= 0.25, random_state=0)  
  
#feature Scaling  
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
X_train= st_x.fit_transform(X_train)    
X_test= st_x.transform(X_test)  

#Fitting K-NN classifier to the training set  
from sklearn.neighbors import KNeighborsClassifier  
classifier= KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2 )  
classifier.fit(X_train, y_train)  



C:\Users\joseph\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:625: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\joseph\Anaconda3\lib\site-packages\sklearn\base.py:462: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
C:\Users\joseph\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')

In [20]:
#Getting the predictions.
#Predicting the test set result  
y_pred= classifier.predict(X_test)  

In [21]:
#Evaluating the Algorithm
#Creating the Confusion matrix  
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[41  6  1]
 [ 3 24  8]
 [ 1  7 63]]
              precision    recall  f1-score   support

           3       0.91      0.85      0.88        48
           4       0.65      0.69      0.67        35
           5       0.88      0.89      0.88        71

   micro avg       0.83      0.83      0.83       154
   macro avg       0.81      0.81      0.81       154
weighted avg       0.83      0.83      0.83       154

